# Generated by Django 3.2.9 on 2022-03-12 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0003_order_user_profile'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('order_status', models.IntegerField(choices=[(0, 'Ordered'), (1, 'Delivering'), (2, 'Recieved'), (3, 'Unknown'), (4, 'Canceled')], default=0)),
                ('review', models.TextField(default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_reviews', to='profiles.userprofile')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='checkout.order')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='order_history.orderreview')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_comments', to='profiles.userprofile')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
