# Generated by Django 3.2.9 on 2022-03-10 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_remove_product_has_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('problem_type', models.IntegerField(choices=[(0, 'Damaged'), (1, 'Quality Problem'), (2, 'Others')], default=0)),
                ('problem_description', models.TextField(default='')),
                ('report_on', models.DateTimeField(auto_now_add=True)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=50)),
                ('checked', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_report', to='products.product')),
            ],
            options={
                'ordering': ['-report_on'],
            },
        ),
    ]
