# Generated by Django 3.2.9 on 2022-03-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=50, null=True),
        ),
    ]
