# Generated by Django 3.2.9 on 2022-03-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='other_contact',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
